name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Setup gorc
      run: go get github.com/stretchr/gorc

    #- name: Build
      #run: go build -v ./...

    - name: Test with gorc
      run: gorc test -v -cover

    - name: Test hello pkg
      run: go test -v -cover github.com/rjar2020/learn-go-with-tests/hello

    - name: Test ints pkg
      run: go test -v -cover github.com/rjar2020/learn-go-with-tests/ints
      
    - name: Test iteration pkg
      run: go test -v -cover github.com/rjar2020/learn-go-with-tests/iteration
    
    - name: Test collections pkg
      run: go test -v -cover github.com/rjar2020/learn-go-with-tests/slices
    
    - name: Test collections pkg
      run: go test -v -cover github.com/rjar2020/learn-go-with-tests/structs
