name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - name: Setup dependencies
      run: go get github.com/stretchr/gorc; go get -u github.com/kisielk/errcheck

    - name: Linter step - find unchecked errors
      run: errcheck ./...

    - name: Test with gorc
      run: gorc test
